site:
  title: Local Tests
  # features that depend on the site URL: https://docs.antora.org/antora/2.3/playbook/site-url/#when-should-the-site-url-be-set
  url: https://documentation.bonitasoft.com/
  start_page: bonita::index.adoc
  robots: allow

output:
  clean: true

# see https://docs.antora.org/antora/2.3/playbook/configure-runtime/
runtime:
  cache_dir: ./.cache/antora
  log:
    # use pretty even on CI
    format: pretty
    level: info

content:
  sources:
    - url: ./
      start_paths:
        - ./resources/local-content-for-tests/bonita/v2021.2
        - ./resources/local-content-for-tests/bonita/v2021.1
        - ./resources/local-content-for-tests/bonita/v7.11
        - ./resources/local-content-for-tests/bonita/v0
        # Simulate 2022.1 alpha
        # - ./resources/local-content-for-tests/bonita/v1-for-2022.1-alpha
        # Simulate 2022.1 beta
        - ./resources/local-content-for-tests/bonita/v2022.1-beta
        # Also starting 2022.2 alpha
        - ./resources/local-content-for-tests/bonita/v1-for-2022.2-alpha
      branches: HEAD
ui:
  bundle:
#    url: ./resources/local-content-for-tests/default-ui-bundle.zip
      url: ./resources/antora-ui-bundle.zip

antora:
  extensions:
    - id: versions-sorter
      require: ./lib/antora/versions-sorter-extension.js
      enabled: true

asciidoc:
  # Only enable for preview, we don't care for production and it can have performance impacts
  # https://docs.antora.org/antora/3.0/playbook/asciidoc-sourcemap/
  sourcemap: false
  extensions:
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/tabs-block.js
urls:
#  html_extension_style: default
#  redirect_facility: static
  # For netlify tests
  html_extension_style: drop
  redirect_facility: netlify
  ##### new with Antora 3.0
  latest_version_segment: latest
  latest_prerelease_version_segment: next
  latest_version_segment_strategy: redirect:to
