site:
  title: Local Tests
  # features that depend on the site URL: https://docs.antora.org/antora/2.3/playbook/site-url/#when-should-the-site-url-be-set
  url: https://documentation.bonitasoft.com/
  start_page: bonita::index.adoc
  robots: allow

# see https://docs.antora.org/antora/2.3/playbook/configure-runtime/
runtime:
  cache_dir: ./.cache/antora

content:
  sources:
    - url: ./
      start_paths:
        - ./resources/local-content-for-tests/bonita/v2021.1
        - ./resources/local-content-for-tests/bonita/v7.11
        - ./resources/local-content-for-tests/bonita/v0
        - ./resources/local-content-for-tests/bonita/v1-prerelease
      branches: HEAD
ui:
  bundle:
    url: ./resources/local-content-for-tests/default-ui-bundle.zip
#      url: ./resources/antora-ui-bundle.zip

asciidoc:
  # Only enable for preview, we don't care for production and it can have performance impacts
  # https://docs.antora.org/antora/3.0/playbook/asciidoc-sourcemap/
  sourcemap: false
  extensions:
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/tabs-block.js
urls:
  html_extension_style: default
  redirect_facility: static
#  html_extension_style: drop
#  redirect_facility: netlify
  ##### new with Antora 3.0
#  latest_version_segment: latest
#  latest_prerelease_version_segment: next
#  latest_version_segment_strategy: redirect:to
