site:
  title: Bonita Documentation
  # features that depend on the site URL: https://docs.antora.org/antora/2.3/playbook/site-url/#when-should-the-site-url-be-set
  url: https://documentation.bonitasoft.com/
  start_page: bonita::index.adoc
  robots: allow

# see https://docs.antora.org/antora/2.3/playbook/configure-runtime/
runtime:
  cache_dir: ./.cache/antora

content:
  # When adding a new url, add a new entry in generate-content-for-preview-antora-playbook.js to manage PR preview
  # The site preview only use the latest declared branch for each source
  sources:
    - url: https://github.com/bonitasoft/bonita-cloud-doc.git
      branches:
        - "master"
    - url: https://github.com/bonitasoft/bonita-doc.git
      branches:
        - "archives"
        - "7.6"
        - "7.7"
        - "7.8"
        - "7.9"
        - "7.10"
        - "7.11"
        - "2021.1"
        - "2021.2"
        - "2022.1"
    - url: https://github.com/bonitasoft/bonita-ici-doc.git
      branches:
        - "master"
    - url: https://github.com/bonitasoft/bonita-continuous-delivery-doc.git
      branches:
        - "3.4"
        - "3.5"
ui:
  bundle:
    url: ./resources/antora-ui-bundle.zip

asciidoc:
  # Only enable for preview, we don't care for production and it can have performance impacts
  # https://docs.antora.org/antora/3.0/playbook/asciidoc-sourcemap/
  sourcemap: false
  extensions:
    - ./lib/source-url-include-processor.js
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/tabs-block.js
urls:
  html_extension_style: drop
  redirect_facility: netlify
  ##### new with Antora 3.0
  latest_version_segment: latest
  latest_prerelease_version_segment: next
#  what we target
#  latest_version_segment_strategy: redirect:to
#  to simulate what we have now
  latest_version_segment_strategy: redirect:to
